version: "3.8"
services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_KRAFT_MODE: "true"
      KAFKA_CFG_KRAFT_STORAGE_ROOT_DIR: /bitnami/kafka/data
      KAFKA_CFG_KRAFT_METADATA_LOG_DIRS: /bitnami/kafka/meta
      KAFKA_OPTS: "-Duser.timezone=Asia/Taipei"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LOG_RETENTION_MINUTES: "5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/bitnami/kafka
    # 要考慮不要設定，不然log太多
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    networks:
      - kafka-net

  app:
    build: .
    container_name: kafka-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 3G
    networks:
      - kafka-net

# networks:
#   kafka-net:
#     driver: overlay
#     attachable: true
volumes:
  kafka_data:
    driver: local
# 本地------------------------------------------
networks:
  kafka-net:
    driver: bridge
