services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    # cpus: 0.375
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - kafka-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      # - SPARK_WORKER_CORES=1 # 這邊是對內宣稱，worker可以用滿分配的0.75
      # - SPARK_WORKER_MEMORY=1G
    # cpus: 0.75
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - kafka-net

  spark-driver:
    image: bitnami/spark:latest
    container_name: spark-driver
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./sp:/opt/spark-apps
      - ./.ivy2:/opt/bitnami/spark/.ivy2
      - ./checkpoints:/app/tmp/spark_checkpoints # 添加這行

    working_dir: /opt/spark-apps
    command: >
      bash -c "
      mkdir -p /opt/bitnami/spark/.ivy2/local &&
      spark-submit
      --conf spark.sql.session.timeZone=Asia/Taipei
      --conf spark.jars.ivy=/opt/bitnami/spark/.ivy2 
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 
      --master spark://spark-master:7077 
      /opt/spark-apps/spark_application_first.py
      "
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - kafka-net
networks:
  kafka-net:
    external:
      name: stock-kafka_kafka-net
