services:
  spark-driver-sec:
    image: bitnami/spark:latest
    container_name: spark-driver-sec
    # environment:
    #   - SPARK_MODE=client
    #   - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./sp:/opt/spark-apps
      - ./.ivy2:/opt/bitnami/spark/.ivy2
      - ./checkpoints:/app/tmp/spark_checkpoints

    working_dir: /opt/spark-apps
    ports:
      - "4040-4045:4040-4045"
    command: >
      bash -c "
      pip install kafka-python &&
      mkdir -p /opt/bitnami/spark/.ivy2/local &&
      spark-submit
      --master local[2]
      --conf spark.sql.session.timeZone=Asia/Taipei
      --conf spark.jars.ivy=/opt/bitnami/spark/.ivy2 
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2,org.apache.kafka:kafka-clients:3.8.0
      --master spark://spark-master:7077 
      /opt/spark-apps/spark_application_first.py
      "
    networks:
      - kafka-net

  spark-driver-ma:
    image: bitnami/spark:latest
    container_name: spark-driver-ma
    # environment:
    #   - SPARK_MODE=client
    #   - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./sp:/opt/spark-apps
      - ./.ivy2:/opt/bitnami/spark/.ivy2
      - ./checkpoints:/app/tmp/spark_checkpoints
    working_dir: /opt/spark-apps
    ports:
      - "4046-4050:4046-4050"
    command: >
      bash -c "
      pip install kafka-python &&
      mkdir -p /opt/bitnami/spark/.ivy2/local &&
      spark-submit
      --master local[2]
      --conf spark.sql.session.timeZone=Asia/Taipei
      --conf spark.jars.ivy=/opt/bitnami/spark/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2,org.apache.kafka:kafka-clients:3.8.0
      --master spark://spark-master:7077
      /opt/spark-apps/spark_ma.py
      "
    networks:
      - kafka-net

# networks:
#   kafka-net:
#     external: true
# 本地------------------------------------------
networks:
  kafka-net:
    external:
      name: stock-kafka_kafka-net
# -----------------------------------------------------------------------------
# spark-master:
#   image: bitnami/spark:latest
#   container_name: spark-master
#   environment:
#     - SPARK_MODE=master
#     - SPARK_MASTER_HOST=spark-master
#     - SPARK_RPC_AUTHENTICATION_ENABLED=no
#     - SPARK_RPC_ENCRYPTION_ENABLED=no
#     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#     - SPARK_SSL_ENABLED=no
#   # cpus: 0.375
#   ports:
#     - "7077:7077"
#     - "8080:8080"
#   networks:
#     - kafka-net

# spark-worker:
#   image: bitnami/spark:latest
#   container_name: spark-worker
#   environment:
#     - SPARK_MODE=worker
#     - SPARK_MASTER_URL=spark://spark-master:7077
#     # - SPARK_WORKER_CORES=1 # 這邊是對內宣稱，worker可以用滿分配的0.75
#     # - SPARK_WORKER_MEMORY=1G
#   # cpus: 0.75
#   depends_on:
#     - spark-master
#   ports:
#     - "8081:8081"
#   networks:
#     - kafka-net
