version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper

    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka

    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - kafka-net

# 這邊一以定要設定，不然連接不上
networks:
  kafka-net:
    driver: bridge
