services:
  fastapi-app:
    image: raphafang/fastapi-app:latest
    # deploy:
    #   placement:
    #     constraints:
    #       - "node.hostname == ip-10-0-1-114"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
    environment:
      KAFKA_BROKER: 10.0.1.138:9092
      SPARK_LOCAL_IP: 10.0.1.231
      SPARK_PUBLIC_DNS: 10.0.1.231
    # networks:
    #   - kafka-net
    #   - aws-net
    # volumes:
    #   - /home/ubuntu/WH/tdt/secrets:/app/secrets
# networks:
#   kafka-net:
#     name: kafka_stack_kafka-net
#     external: true
#   aws-net:
#     external: true
# name: vpc-0732371fa974ce172
# 本地------------------------------------------
# networks:
#   kafka-net:
#     name: kafka_stack_kafka-net
#     external: true
# environment:
#   - SQL_USER=${SQL_USER}
#   - SQL_PASSWORD=${SQL_PASSWORD}
#   - PRIVATE_KEY_PATH=/app/secrets/private_key.pem
#   - PUBLIC_KEY_PATH=/app/secrets/public_key.pem
#   - REDIS_PASSWORD=${REDIS_PASSWORD}
#   - TAP_PARTNER_KEY=${TAP_PARTNER_KEY}
#   - MERCHANT_ID=${MERCHANT_ID}
#   - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#   - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#   - GOOGLE_SESSION_SECRET_KEY=${GOOGLE_SESSION_SECRET_KEY}
#   - PERSONAL_GMAIL=${PERSONAL_GMAIL}
#   - PERSONAL_GMAIL_PASSWORD=${PERSONAL_GMAIL_PASSWORD}
